# Generated by Django 4.0 on 2024-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('movie_name', models.CharField(max_length=30)),
                ('hero_name', models.CharField(max_length=30)),
                ('heroien_name', models.CharField(max_length=30)),
                ('movie_rating', models.FloatField()),
            ],
        ),
    ]
